DROP TABLE EDUCATOR;
DROP TABLE USERS;
DROP TABLE IMAGE;
/*DROP TABLE COMMENT;*/
DROP TABLE COORDINATES;
DROP TABLE RESULTS;
DROP TABLE TASK;
DROP TABLE PRESCHOOLER;
DROP TABLE GROUPS;
DROP TABLE TEST;
DROP TABLE LOCATION;

CREATE TABLE USERS (
	userID					INTEGER			AUTO_INCREMENT,
	username				VARCHAR(100)	NOT NULL,
	password				VARCHAR(100)	NOT NULL,
	email					VARCHAR(100)	NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (userID)
);

CREATE TABLE EDUCATOR (
	userID					INTEGER			NOT NULL,
	locationID				INTEGER			NOT NULL,
	/*firstName				VARCHAR(200)	NOT NULL,
	lastName				VARCHAR(200)	NOT NULL*/
	CONSTRAINT educator_pk PRIMARY KEY (userID),
	CONSTRAINT educator_fk FOREIGN KEY (locationID) REFERENCES LOCATION (locationID)
);

CREATE TABLE TEST(
	testID					INTEGER		AUTO_INCREMENT,
	dateCreated				DATE		NOT NULL,
	dateEdited				DATE		NULL,
	numberOfParticipants	INTEGER		NOT NULL,
	numberOfQuestions		INTEGER		NOT NULL,
	locationID				INTEGER		NOT NULL,
	CONSTRAINT test_pk PRIMARY KEY (testID),
	CONSTRAINT test_fk FOREIGN KEY (locationID) REFERENCES LOCATION (locationID)
);

CREATE TABLE LOCATION (
	locationID				INTEGER			AUTO_INCREMENT,
	name					VARCHAR(500)	NOT NULL,
	CONSTRAINT location_pk PRIMARY KEY (locationID)
);

CREATE TABLE GROUPS (
	groupID					INTEGER			AUTO_INCREMENT,
	name					VARCHAR(500)	NOT NULL,
	locationID				INTEGER			NOT NULL,
	CONSTRAINT group_pk PRIMARY KEY (groupID),
	CONSTRAINT group_fk FOREIGN KEY (locationID) REFERENCES LOCATION (locationID)
);

CREATE TABLE PRESCHOOLER(
	preID					INTEGER			AUTO_INCREMENT,
	name					VARCHAR(300)	NOT NULL,
	age 					INTEGER			NOT NULL,
	gender					VARCHAR(100)	NOT NULL,
	groupID					INTEGER			NULL,
	CONSTRAINT preschooler_pk PRIMARY KEY (preID),
	CONSTRAINT preschooler_fk FOREIGN KEY (groupID) REFERENCES GROUPS(groupID)
);

CREATE TABLE TASK(
	taskID					INTEGER			AUTO_INCREMENT,
	instruction				VARCHAR(700)	NOT NULL,
	questionType			VARCHAR(500)	NOT NULL,
	content					VARCHAR(500)	NOT NULL,
	comments				VARCHAR(700)	NULL,
	testID					INTEGER			NOT NULL,
	CONSTRAINT task_pk PRIMARY KEY (taskID),
	CONSTRAINT task_fk FOREIGN KEY (testID) REFERENCES TEST(testID)
);

CREATE TABLE IMAGE(
	imageID					INTEGER			AUTO_INCREMENT,
	address					VARCHAR(300)	NOT NULL,
	taskID					INTEGER			NOT NULL,
	CONSTRAINT image_pk PRIMARY KEY (imageID),
	CONSTRAINT image_fk FOREIGN KEY (taskID) REFERENCES TASK(taskID)
);
/*
CREATE TABLE COMMENT(
	content					VARCHAR(700)	NOT NULL,
	commentType				VARCHAR(500)	NOT NULL,
	questionID				INTEGER			NOT NULL,
	CONSTRAINT comment_pk PRIMARY KEY (comment),
	CONSTRAINT commemt_fk FOREIGN KEY (questionID) REFERENCES QUESTION(questionID)
);
*/
CREATE TABLE RESULTS(
	resultID				INTEGER			AUTO_INCREMENT,
	answer					VARCHAR(500)	NOT NULL,
	/*mechanic				VARCHAR(500)	NOT NULL,*/
	dateCollected			DATE			NOT NULL,
	taskID					INTEGER			NOT NULL,
	preID					INTEGER			NOT NULL,
	CONSTRAINT result_pk PRIMARY KEY (resultID),
	CONSTRAINT result_fk1 FOREIGN KEY (taskID) REFERENCES TASK (taskID),
	CONSTRAINT result_fk2 FOREIGN KEY (preID) REFERENCES PRESCHOOLER (preID)
);

CREATE TABLE COORDINATES(
	/*numberOfTouches			INTEGER			NOT NULL,*/
	xCoord					DECIMAL			NULL,
	yCoord					DECIMAL			NULL,
	resultID				INTEGER			NOT NULL,
	/*preID					INTEGER			NOT NULL,
	imageID					INTEGER			NOT NULL,*/
	CONSTRAINT coords_fk FOREIGN KEY (resultID) REFERENCES RESULTS(resultID)
);