DROP TABLE IMAGE;
DROP TABLE TASK;
DROP TABLE PRESCHOOLER;
DROP TABLE GROUPTEST;
DROP TABLE TEST;
DROP TABLE LOCATION;
/**/
CREATE TABLE LOCATION(
	locationID				INTEGER			AUTO_INCREMENT,
	name					VARCHAR(500)	NOT NULL,
	CONSTRAINT location_pk PRIMARY KEY (locationID)
);

CREATE TABLE TEST(
	testID					INTEGER			AUTO_INCREMENT,
	testName				VARCHAR(300)	NOT NULL,
	description				VARCHAR(800)	NOT NULL,
	CONSTRAINT test_pk PRIMARY KEY (testID)
);

CREATE TABLE GROUPTEST(
	groupID					INTEGER			AUTO_INCREMENT,
	groupName					VARCHAR(500)	NOT NULL,
	CONSTRAINT group_pk PRIMARY KEY (groupID)
);

CREATE TABLE PRESCHOOLER(
	preID					INTEGER			AUTO_INCREMENT,
	name					VARCHAR(300)	NOT NULL,
	age 					INTEGER			NOT NULL,
	gender					VARCHAR(100)	NOT NULL,
	groupID					INTEGER			NULL,
	CONSTRAINT preschooler_pk PRIMARY KEY (preID),
	CONSTRAINT preschooler_fk FOREIGN KEY (groupID) REFERENCES GROUPTEST(groupID)
);

CREATE TABLE TASK(
	taskID				INTEGER			AUTO_INCREMENT,
	instruction				VARCHAR(700)	NOT NULL,
	questionType			VARCHAR(500)	NOT NULL,
	comments				VARCHAR(700)	NULL,
	testID					INTEGER			NOT NULL,
	CONSTRAINT task_pk PRIMARY KEY (taskID),
	CONSTRAINT task_fk FOREIGN KEY (testID) REFERENCES TEST(testID)
);

CREATE TABLE IMAGE(
	imageID					INTEGER			AUTO_INCREMENT,
	address					VARCHAR(300)	NOT NULL,
	taskID					INTEGER			NOT NULL,
	CONSTRAINT image_pk PRIMARY KEY (imageID),
	CONSTRAINT image_fk FOREIGN KEY (taskID) REFERENCES TASK(taskID)
);
